spring:
  config:
    activate:
      on-profile: "dev"

author:
  authorName: "{cipher}ff4b6c16524fc4794d82860c70ff994fe6a0e92ca7bf7f841955a55dcfb5c999ae52861ed8dc6309e1056bc1dfb278d5"
  contactInfo:
    1: "123456789000"
    2: "dev823758366"
  otherNames:
    - this is got from github
    - when after callin the bus refresher

